name: ts_intro
channels:
- defaults
- conda-forge
dependencies:
- ipykernel>=4.6.1
- jupyter>=1.0.0
- numpy>=1.13.3
- pandas>=0.23.4
- python==3.6.9
- seaborn==0.9.0
- pip:
  - matplotlib==3.1.1
  - scikit-learn==0.21.3
  - keras==2.3.1
  - tensorflow==1.15
